import PDFDocument from 'pdfkit';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const LOGO_PATH = path.join(__dirname, '../assets/logo.png');

/**
 * Simple PDF Report Service for Competitor Intelligence
 * Generates clean, data-driven reports with actual analysis metrics
 */
class PDFReportService {
  constructor() {
    this.colors = {
      primary: '#1f2937',
      secondary: '#6b7280',
      accent: '#f97316',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444'
    };
  }

  /**
   * Generate competitor analysis PDF report
   */
  async generateCompetitorReport(data) {
    return new Promise((resolve, reject) => {
      try {
        console.log('📄 PDF Generation - Input data keys:', Object.keys(data || {}));

        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 50, bottom: 50, left: 50, right: 50 }
        });

        const chunks = [];
        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // Extract data with fallbacks
        const yourSite = data.yourSite || {};
        const competitorSite = data.competitorSite || {};
        const comparison = data.comparison || {};
        const yourDomain = data.yourSite?.domain || data.yourSite || 'Your Site';
        const compDomain = data.competitorSite?.domain || data.competitorSite || 'Competitor';

        console.log('📄 PDF - Your site keys:', Object.keys(yourSite));
        console.log('📄 PDF - Competitor site keys:', Object.keys(competitorSite));
        console.log('📄 PDF - Comparison keys:', Object.keys(comparison));

        // Page 1: Cover
        this.addCover(doc, yourDomain, compDomain);

        // Page 2: Executive Summary with real data
        doc.addPage();
        this.addExecutiveSummary(doc, yourSite, competitorSite, comparison);

        // Page 3: SEO & Performance
        doc.addPage();
        this.addSEOPerformance(doc, yourSite, competitorSite, comparison);

        // Page 4: Social Media
        doc.addPage();
        this.addSocialMedia(doc, yourSite, competitorSite);

        // Page 5: Technical Analysis
        doc.addPage();
        this.addTechnicalAnalysis(doc, yourSite, competitorSite);

        // Page 6: Recommendations
        doc.addPage();
        this.addRecommendations(doc, comparison);

        // Add page numbers
        this.addPageNumbers(doc);

        doc.end();
      } catch (error) {
        console.error('PDF Generation Error:', error);
        reject(error);
      }
    });
  }

  addCover(doc, yourDomain, compDomain) {
    // Add Claryx logo at the top center
    try {
      if (fs.existsSync(LOGO_PATH)) {
        doc.image(LOGO_PATH, 240, 80, { width: 80, height: 80 });
      }
    } catch (error) {
      console.warn('⚠️ Could not load logo:', error.message);
    }

    doc.fontSize(28)
      .fillColor(this.colors.primary)
      .text('Competitor Intelligence Report', 50, 200, { align: 'center' });

    doc.fontSize(16)
      .fillColor(this.colors.secondary)
      .text(`${yourDomain} vs ${compDomain}`, 50, 250, { align: 'center' });

    doc.fontSize(12)
      .fillColor(this.colors.secondary)
      .text(`Generated: ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
      })}`, 50, 300, { align: 'center' });

    doc.rect(50, 400, 495, 2)
      .fillColor(this.colors.accent)
      .fill();

    doc.fontSize(8)
      .fillColor(this.colors.secondary)
      .text('Generated by CLARYX Analytics Platform', 50, 720, { align: 'center' });
  }

  addExecutiveSummary(doc, yourSite, competitorSite, comparison) {
    doc.fontSize(20)
      .fillColor(this.colors.primary)
      .text('Executive Summary', 50, 50);

    doc.moveTo(50, 80).lineTo(200, 80).strokeColor(this.colors.accent).lineWidth(2).stroke();

    let y = 100;

    // Overall comparison scores
    doc.fontSize(14).fillColor(this.colors.primary).text('Performance Comparison', 50, y);
    y += 25;

    // SEO Score
    const yourSEO = comparison?.seo?.yours || yourSite?.lighthouse?.categories?.seo?.score * 100 || 0;
    const compSEO = comparison?.seo?.competitor || competitorSite?.lighthouse?.categories?.seo?.score * 100 || 0;
    this.addComparisonRow(doc, 'SEO Score', Math.round(yourSEO), Math.round(compSEO), y);
    y += 30;

    // Performance Score
    const yourPerf = comparison?.performance?.yours || yourSite?.lighthouse?.categories?.performance?.score * 100 || 0;
    const compPerf = comparison?.performance?.competitor || competitorSite?.lighthouse?.categories?.performance?.score * 100 || 0;
    this.addComparisonRow(doc, 'Performance Score', Math.round(yourPerf), Math.round(compPerf), y);
    y += 30;

    // Accessibility Score
    const yourAcc = yourSite?.lighthouse?.categories?.accessibility?.score * 100 || 0;
    const compAcc = competitorSite?.lighthouse?.categories?.accessibility?.score * 100 || 0;
    this.addComparisonRow(doc, 'Accessibility', Math.round(yourAcc), Math.round(compAcc), y);
    y += 30;

    // Best Practices
    const yourBP = yourSite?.lighthouse?.categories?.['best-practices']?.score * 100 || 0;
    const compBP = competitorSite?.lighthouse?.categories?.['best-practices']?.score * 100 || 0;
    this.addComparisonRow(doc, 'Best Practices', Math.round(yourBP), Math.round(compBP), y);
    y += 50;

    // Domain Authority / Backlinks
    doc.fontSize(14).fillColor(this.colors.primary).text('Authority & Visibility', 50, y);
    y += 25;

    const yourBacklinks = comparison?.backlinks?.yours || yourSite?.backlinks?.count || 0;
    const compBacklinks = comparison?.backlinks?.competitor || competitorSite?.backlinks?.count || 0;
    this.addComparisonRow(doc, 'Backlinks', yourBacklinks, compBacklinks, y, true);
    y += 30;

    const yourDA = yourSite?.domainAuthority || yourSite?.seo?.domainAuthority || 0;
    const compDA = competitorSite?.domainAuthority || competitorSite?.seo?.domainAuthority || 0;
    this.addComparisonRow(doc, 'Domain Authority', yourDA, compDA, y);
    y += 50;

    // Key Insights
    doc.fontSize(14).fillColor(this.colors.primary).text('Key Insights', 50, y);
    y += 25;

    const insights = this.generateInsights(yourSite, competitorSite, comparison);
    doc.fontSize(10).fillColor(this.colors.secondary);
    insights.forEach(insight => {
      doc.text(`• ${insight}`, 60, y, { width: 480 });
      y += 20;
    });
  }

  addSEOPerformance(doc, yourSite, competitorSite, comparison) {
    doc.fontSize(20)
      .fillColor(this.colors.primary)
      .text('SEO & Performance Analysis', 50, 50);

    doc.moveTo(50, 80).lineTo(250, 80).strokeColor(this.colors.accent).lineWidth(2).stroke();

    let y = 100;

    // Core Web Vitals
    doc.fontSize(14).fillColor(this.colors.primary).text('Core Web Vitals', 50, y);
    y += 25;

    // LCP
    const yourLCP = yourSite?.pagespeed?.mobile?.labData?.lcp || yourSite?.lighthouse?.audits?.['largest-contentful-paint']?.numericValue || 0;
    const compLCP = competitorSite?.pagespeed?.mobile?.labData?.lcp || competitorSite?.lighthouse?.audits?.['largest-contentful-paint']?.numericValue || 0;
    this.addMetricRow(doc, 'Largest Contentful Paint (LCP)',
      yourLCP ? `${(yourLCP / 1000).toFixed(2)}s` : 'N/A',
      compLCP ? `${(compLCP / 1000).toFixed(2)}s` : 'N/A', y);
    y += 25;

    // FID/TBT
    const yourTBT = yourSite?.pagespeed?.mobile?.labData?.tbt || yourSite?.lighthouse?.audits?.['total-blocking-time']?.numericValue || 0;
    const compTBT = competitorSite?.pagespeed?.mobile?.labData?.tbt || competitorSite?.lighthouse?.audits?.['total-blocking-time']?.numericValue || 0;
    this.addMetricRow(doc, 'Total Blocking Time (TBT)',
      yourTBT ? `${Math.round(yourTBT)}ms` : 'N/A',
      compTBT ? `${Math.round(compTBT)}ms` : 'N/A', y);
    y += 25;

    // CLS
    const yourCLS = yourSite?.pagespeed?.mobile?.labData?.cls || yourSite?.lighthouse?.audits?.['cumulative-layout-shift']?.numericValue || 0;
    const compCLS = competitorSite?.pagespeed?.mobile?.labData?.cls || competitorSite?.lighthouse?.audits?.['cumulative-layout-shift']?.numericValue || 0;
    this.addMetricRow(doc, 'Cumulative Layout Shift (CLS)',
      yourCLS !== undefined ? yourCLS.toFixed(3) : 'N/A',
      compCLS !== undefined ? compCLS.toFixed(3) : 'N/A', y);
    y += 40;

    // Page Speed Scores
    doc.fontSize(14).fillColor(this.colors.primary).text('PageSpeed Scores', 50, y);
    y += 25;

    const yourMobileScore = yourSite?.pagespeed?.mobile?.score || 0;
    const compMobileScore = competitorSite?.pagespeed?.mobile?.score || 0;
    this.addComparisonRow(doc, 'Mobile Score', Math.round(yourMobileScore), Math.round(compMobileScore), y);
    y += 30;

    const yourDesktopScore = yourSite?.pagespeed?.desktop?.score || 0;
    const compDesktopScore = competitorSite?.pagespeed?.desktop?.score || 0;
    this.addComparisonRow(doc, 'Desktop Score', Math.round(yourDesktopScore), Math.round(compDesktopScore), y);
    y += 50;

    // SEO Technical Details
    doc.fontSize(14).fillColor(this.colors.primary).text('SEO Technical Details', 50, y);
    y += 25;

    // Meta tags
    const yourMeta = comparison?.seo?.metaTags?.your || {};
    const compMeta = comparison?.seo?.metaTags?.competitor || {};

    this.addMetricRow(doc, 'Title Tag',
      yourMeta.hasTitle ? '✓ Present' : '✗ Missing',
      compMeta.hasTitle ? '✓ Present' : '✗ Missing', y);
    y += 25;

    this.addMetricRow(doc, 'Meta Description',
      yourMeta.hasDescription ? '✓ Present' : '✗ Missing',
      compMeta.hasDescription ? '✓ Present' : '✗ Missing', y);
    y += 25;

    // Headings
    const yourH1 = comparison?.seo?.headings?.your?.h1Count || yourSite?.seo?.h1Count || 0;
    const compH1 = comparison?.seo?.headings?.competitor?.h1Count || competitorSite?.seo?.h1Count || 0;
    this.addMetricRow(doc, 'H1 Tags', yourH1.toString(), compH1.toString(), y);
    y += 25;

    const yourH2 = comparison?.seo?.headings?.your?.h2Count || yourSite?.seo?.h2Count || 0;
    const compH2 = comparison?.seo?.headings?.competitor?.h2Count || competitorSite?.seo?.h2Count || 0;
    this.addMetricRow(doc, 'H2 Tags', yourH2.toString(), compH2.toString(), y);
  }

  addSocialMedia(doc, yourSite, competitorSite) {
    doc.fontSize(20)
      .fillColor(this.colors.primary)
      .text('Social Media Presence', 50, 50);

    doc.moveTo(50, 80).lineTo(220, 80).strokeColor(this.colors.accent).lineWidth(2).stroke();

    let y = 100;

    // Instagram
    doc.fontSize(14).fillColor(this.colors.primary).text('Instagram', 50, y);
    y += 25;

    const yourIG = yourSite?.instagram?.profile || yourSite?.instagram?.metrics || {};
    const compIG = competitorSite?.instagram?.profile || competitorSite?.instagram?.metrics || {};

    const yourIGFollowers = yourIG.followers || yourSite?.instagram?.metrics?.followers || 0;
    const compIGFollowers = compIG.followers || competitorSite?.instagram?.metrics?.followers || 0;
    this.addMetricRow(doc, 'Followers',
      yourIGFollowers ? yourIGFollowers.toLocaleString() : 'N/A',
      compIGFollowers ? compIGFollowers.toLocaleString() : 'N/A', y);
    y += 25;

    const yourIGEngagement = yourIG.avgEngagementRate || yourSite?.instagram?.engagement?.avgEngagement || 0;
    const compIGEngagement = compIG.avgEngagementRate || competitorSite?.instagram?.engagement?.avgEngagement || 0;
    this.addMetricRow(doc, 'Avg Engagement Rate',
      yourIGEngagement ? `${(yourIGEngagement * 100).toFixed(2)}%` : 'N/A',
      compIGEngagement ? `${(compIGEngagement * 100).toFixed(2)}%` : 'N/A', y);
    y += 40;

    // Facebook
    doc.fontSize(14).fillColor(this.colors.primary).text('Facebook', 50, y);
    y += 25;

    const yourFB = yourSite?.facebook?.metrics || yourSite?.facebook?.data || {};
    const compFB = competitorSite?.facebook?.metrics || competitorSite?.facebook?.data || {};

    const yourFBFollowers = yourFB.followers || yourSite?.facebook?.metrics?.followers || 0;
    const compFBFollowers = compFB.followers || competitorSite?.facebook?.data?.followers || 0;
    this.addMetricRow(doc, 'Followers',
      yourFBFollowers ? yourFBFollowers.toLocaleString() : 'N/A',
      compFBFollowers ? compFBFollowers.toLocaleString() : 'N/A', y);
    y += 25;

    const yourFBEngagement = yourFB.engagementRate || 0;
    const compFBEngagement = compFB.engagementRate || 0;
    this.addMetricRow(doc, 'Engagement Rate',
      yourFBEngagement ? `${yourFBEngagement.toFixed(2)}%` : 'N/A',
      compFBEngagement ? `${compFBEngagement.toFixed(2)}%` : 'N/A', y);
    y += 40;

    // LinkedIn
    doc.fontSize(14).fillColor(this.colors.primary).text('LinkedIn', 50, y);
    y += 25;

    const yourLI = yourSite?.linkedin || {};
    const compLI = competitorSite?.linkedin || {};

    const yourLIFollowers = yourLI.companyFollowers || 0;
    const compLIFollowers = compLI.companyFollowers || 0;
    this.addMetricRow(doc, 'Company Followers',
      yourLIFollowers ? yourLIFollowers.toLocaleString() : 'N/A',
      compLIFollowers ? compLIFollowers.toLocaleString() : 'N/A', y);
    y += 25;

    const yourLIEngagement = yourLI.engagementScore?.engagementRate || yourLI.metrics?.engagementRate || 0;
    const compLIEngagement = compLI.engagementScore?.engagementRate || compLI.metrics?.engagementRate || 0;
    this.addMetricRow(doc, 'Engagement Rate',
      yourLIEngagement ? `${yourLIEngagement.toFixed(2)}%` : 'N/A',
      compLIEngagement ? `${compLIEngagement.toFixed(2)}%` : 'N/A', y);
  }

  addTechnicalAnalysis(doc, yourSite, competitorSite) {
    doc.fontSize(20)
      .fillColor(this.colors.primary)
      .text('Technical Analysis', 50, 50);

    doc.moveTo(50, 80).lineTo(200, 80).strokeColor(this.colors.accent).lineWidth(2).stroke();

    let y = 100;

    // Security
    doc.fontSize(14).fillColor(this.colors.primary).text('Security', 50, y);
    y += 25;

    const yourHTTPS = yourSite?.security?.isHTTPS !== false;
    const compHTTPS = competitorSite?.security?.isHTTPS !== false;
    this.addMetricRow(doc, 'HTTPS',
      yourHTTPS ? '✓ Enabled' : '✗ Missing',
      compHTTPS ? '✓ Enabled' : '✗ Missing', y);
    y += 40;

    // Technology Stack
    doc.fontSize(14).fillColor(this.colors.primary).text('Technology Stack', 50, y);
    y += 25;

    const yourTech = yourSite?.puppeteer?.technology || yourSite?.technology || {};
    const compTech = competitorSite?.puppeteer?.technology || competitorSite?.technology || {};

    this.addMetricRow(doc, 'CMS',
      yourTech.cms || 'Not detected',
      compTech.cms || 'Not detected', y);
    y += 25;

    this.addMetricRow(doc, 'Frameworks',
      (yourTech.frameworks || []).slice(0, 3).join(', ') || 'None detected',
      (compTech.frameworks || []).slice(0, 3).join(', ') || 'None detected', y);
    y += 25;

    this.addMetricRow(doc, 'Analytics',
      (yourTech.analytics || []).slice(0, 2).join(', ') || 'None detected',
      (compTech.analytics || []).slice(0, 2).join(', ') || 'None detected', y);
    y += 40;

    // Content Analysis
    doc.fontSize(14).fillColor(this.colors.primary).text('Content Metrics', 50, y);
    y += 25;

    const yourWordCount = yourSite?.content?.wordCount || yourSite?.puppeteer?.content?.wordCount || 0;
    const compWordCount = competitorSite?.content?.wordCount || competitorSite?.puppeteer?.content?.wordCount || 0;
    this.addMetricRow(doc, 'Word Count',
      yourWordCount ? yourWordCount.toLocaleString() : 'N/A',
      compWordCount ? compWordCount.toLocaleString() : 'N/A', y);
    y += 25;

    const yourImages = yourSite?.content?.imageCount || yourSite?.puppeteer?.content?.imageCount || 0;
    const compImages = competitorSite?.content?.imageCount || competitorSite?.puppeteer?.content?.imageCount || 0;
    this.addMetricRow(doc, 'Image Count',
      yourImages.toString(),
      compImages.toString(), y);
  }

  addRecommendations(doc, comparison) {
    doc.fontSize(20)
      .fillColor(this.colors.primary)
      .text('Recommendations', 50, 50);

    doc.moveTo(50, 80).lineTo(180, 80).strokeColor(this.colors.accent).lineWidth(2).stroke();

    let y = 110;

    const recommendations = [];

    // Performance recommendations
    if (comparison?.performance?.winner === 'competitor') {
      recommendations.push('Improve page load speed - competitor has faster performance');
    }

    // SEO recommendations
    if (comparison?.seo?.winner === 'competitor') {
      recommendations.push('Focus on SEO optimization - review meta tags, headings, and content structure');
    }

    // Backlinks
    if (comparison?.backlinks?.winner === 'competitor') {
      recommendations.push('Build more quality backlinks to improve domain authority');
    }

    // Default recommendations if none specific
    if (recommendations.length === 0) {
      recommendations.push(
        'Continue monitoring competitor activity regularly',
        'Optimize Core Web Vitals for better user experience',
        'Maintain consistent social media engagement',
        'Focus on creating high-quality, relevant content',
        'Build authoritative backlinks through outreach'
      );
    }

    doc.fontSize(11).fillColor(this.colors.primary).text('Priority Actions:', 50, y);
    y += 25;

    doc.fontSize(10).fillColor(this.colors.secondary);
    recommendations.forEach((rec, index) => {
      doc.text(`${index + 1}. ${rec}`, 60, y, { width: 480 });
      y += 25;
    });

    y += 20;

    // Next steps
    doc.fontSize(11).fillColor(this.colors.primary).text('Implementation Timeline:', 50, y);
    y += 25;

    const timeline = [
      'Week 1-2: Address critical SEO and performance issues',
      'Week 3-4: Implement content improvements',
      'Month 2: Focus on backlink building and social growth',
      'Ongoing: Monitor competitor changes and adapt strategy'
    ];

    doc.fontSize(10).fillColor(this.colors.secondary);
    timeline.forEach(item => {
      doc.text(`• ${item}`, 60, y, { width: 480 });
      y += 20;
    });
  }

  // Helper methods
  addComparisonRow(doc, label, yourValue, compValue, y, isCount = false) {
    doc.fontSize(10)
      .fillColor(this.colors.primary)
      .text(label, 60, y);

    const yourDisplay = isCount ? yourValue.toLocaleString() : yourValue;
    const compDisplay = isCount ? compValue.toLocaleString() : compValue;

    const yourColor = yourValue >= compValue ? this.colors.success : this.colors.secondary;
    const compColor = compValue >= yourValue ? this.colors.success : this.colors.secondary;

    doc.fontSize(10).fillColor(yourColor).text(`Your Site: ${yourDisplay}`, 200, y);
    doc.fontSize(10).fillColor(compColor).text(`Competitor: ${compDisplay}`, 350, y);

    if (yourValue > compValue) {
      doc.fillColor(this.colors.success).text('✓', 500, y);
    } else if (compValue > yourValue) {
      doc.fillColor(this.colors.danger).text('✗', 500, y);
    } else {
      doc.fillColor(this.colors.secondary).text('=', 500, y);
    }
  }

  addMetricRow(doc, label, yourValue, compValue, y) {
    doc.fontSize(10)
      .fillColor(this.colors.secondary)
      .text(label, 60, y)
      .text(`Your Site: ${yourValue}`, 200, y)
      .text(`Competitor: ${compValue}`, 350, y);
  }

  generateInsights(yourSite, competitorSite, comparison) {
    const insights = [];

    // SEO insight
    const yourSEO = comparison?.seo?.yours || 0;
    const compSEO = comparison?.seo?.competitor || 0;
    if (yourSEO > compSEO) {
      insights.push(`Your SEO score is ${yourSEO - compSEO} points higher than competitor`);
    } else if (compSEO > yourSEO) {
      insights.push(`Competitor SEO score is ${compSEO - yourSEO} points ahead - focus on optimization`);
    }

    // Performance insight
    const yourPerf = comparison?.performance?.yours || 0;
    const compPerf = comparison?.performance?.competitor || 0;
    if (yourPerf > compPerf) {
      insights.push('Your site has better performance scores');
    } else if (compPerf > yourPerf) {
      insights.push('Competitor has faster page load times');
    }

    // Social media insight
    const yourIG = yourSite?.instagram?.profile?.followers || yourSite?.instagram?.metrics?.followers || 0;
    const compIG = competitorSite?.instagram?.profile?.followers || competitorSite?.instagram?.metrics?.followers || 0;
    if (yourIG && compIG) {
      if (yourIG > compIG) {
        insights.push(`You have ${Math.round((yourIG / compIG - 1) * 100)}% more Instagram followers`);
      } else if (compIG > yourIG) {
        insights.push(`Competitor has ${Math.round((compIG / yourIG - 1) * 100)}% more Instagram followers`);
      }
    }

    if (insights.length === 0) {
      insights.push('Analysis complete - review detailed metrics for opportunities');
    }

    return insights;
  }

  addPageNumbers(doc) {
    const pages = doc.bufferedPageRange();
    for (let i = pages.start; i < (pages.start + pages.count); i++) {
      doc.switchToPage(i);
      doc.fontSize(8)
        .fillColor(this.colors.secondary)
        .text(`Page ${i - pages.start + 1} of ${pages.count}`, 50, 780, { align: 'center', width: 495 });
    }
  }
}

export default new PDFReportService();